# Site settings
title: "Miles' Blog"
email: miles.matthias@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about software, startups, and mobile technology. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://milesmatthias.com" # the base hostname & protocol for your site
twitter_username: miles_matthias
github_username:  milesmatthias

# Build settings
markdown: kramdown
