# Site settings
title: "Miles Matthias"
email: miles.matthias@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software developer specializing in web and mobile apps. I also enjoy teaching, speaking, and writing books. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://milesmatthias.com" # the base hostname & protocol for your site
twitter_username: miles_matthias
github_username:  milesmatthias

# Build settings
markdown: kramdown
